<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Penghou.Qingniao" Version="0.1.0-preview.4" />
    <PackageReference Include="Penghou.Fuwen" Version="0.1.0-preview.13" />
    <PackageReference Include="Penghou.Fuwen.Zhinu" Version="0.1.0-preview.13" />
    <PackageReference Include="Penghou.Zhinu" Version="0.2.0-preview.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Marang.Mcp\Marang.Mcp.csproj" />
  </ItemGroup>

</Project>
