<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Penghou.Qingniao" Version="0.1.0-preview.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Marang\Marang.csproj" />
    <ProjectReference Include="..\Marang.Mcp\Marang.Mcp.csproj" />
  </ItemGroup>

</Project>
